### ISSUE TITLE
"Can't Open Configure" in build

### ISSUE THREAD

**Issue by someguyiknow** [libyal/libsmdev#4]
~/libsmdev$ sudo python setup.py build
running build
running build_ext
Traceback (most recent call last):
  File "setup.py", line 348, in <module>
    data_files=[(PYTHON_LIBRARY_DIRECTORY, LIBRARY_DATA_FILES)],
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 92, in run
    output = self._RunCommand(command)
  File "setup.py", line 73, in _RunCommand
    command, error))
RuntimeError: Running: sh configure --disable-shared-libs failed with error:
sh: 0: Can't open configure

**Comment by joachimmetz** [comment]
As indicated per chat, this likely clarifies the matter https://github.com/libyal/libsmdev/wiki/Building#read-first
